# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flask_object_detection.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66lask_object_detection.proto\"\x1d\n\robjDetect_pic\x12\x0c\n\x04name\x18\x01 \x01(\t\"Z\n\x0fobjDetect_reply\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x12\x0c\n\x04x_lo\x18\x02 \x01(\t\x12\x0c\n\x04y_lo\x18\x03 \x01(\t\x12\x0c\n\x04x_hi\x18\x04 \x01(\t\x12\x0c\n\x04y_hi\x18\x05 \x01(\t2G\n\x0bobjDetector\x12\x38\n\x12\x61skInfer_objDetect\x12\x0e.objDetect_pic\x1a\x10.objDetect_reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flask_object_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJDETECT_PIC']._serialized_start=32
  _globals['_OBJDETECT_PIC']._serialized_end=61
  _globals['_OBJDETECT_REPLY']._serialized_start=63
  _globals['_OBJDETECT_REPLY']._serialized_end=153
  _globals['_OBJDETECTOR']._serialized_start=155
  _globals['_OBJDETECTOR']._serialized_end=226
# @@protoc_insertion_point(module_scope)
