# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main_server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11main_server.proto\"}\n\x0bintrin_list\x12\x0e\n\x06\x63oeffs\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03ppx\x18\x04 \x01(\x02\x12\x0b\n\x03ppy\x18\x05 \x01(\x02\x12\n\n\x02\x66x\x18\x06 \x01(\x02\x12\n\n\x02\x66y\x18\x07 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x08 \x01(\x0c\"\x17\n\x03img\x12\x10\n\x08img_data\x18\x01 \x01(\x0c\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\x1a\n\x02xy\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\"&\n\x03xyz\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\x12\t\n\x01z\x18\x03 \x01(\t\">\n\x04xyxy\x12\x0c\n\x04x_lo\x18\x01 \x01(\t\x12\x0c\n\x04y_lo\x18\x02 \x01(\t\x12\x0c\n\x04x_hi\x18\x03 \x01(\t\x12\x0c\n\x04y_hi\x18\x04 \x01(\t\"2\n\x06xyznew\x12\x0c\n\x04xnew\x18\x01 \x01(\t\x12\x0c\n\x04ynew\x18\x02 \x01(\t\x12\x0c\n\x04znew\x18\x03 \x01(\t\"2\n\x06xyzmap\x12\x0c\n\x04xnew\x18\x01 \x01(\t\x12\x0c\n\x04ynew\x18\x02 \x01(\t\x12\x0c\n\x04znew\x18\x03 \x01(\t2\xf4\x01\n\x07Greeter\x12*\n\nget_rframe\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x32\n\x12get_infrared_frame\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x16\n\x07\x61sk_xyz\x12\x03.xy\x1a\x04.xyz\"\x00\x12 \n\nask_xyzmap\x12\x07.xyznew\x1a\x07.xyzmap\"\x00\x12+\n\nget_intrin\x12\r.HelloRequest\x1a\x0c.intrin_list\"\x00\x12\"\n\tget_depth\x12\r.HelloRequest\x1a\x04.img\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTRIN_LIST']._serialized_start=21
  _globals['_INTRIN_LIST']._serialized_end=146
  _globals['_IMG']._serialized_start=148
  _globals['_IMG']._serialized_end=171
  _globals['_HELLOREQUEST']._serialized_start=173
  _globals['_HELLOREQUEST']._serialized_end=201
  _globals['_HELLOREPLY']._serialized_start=203
  _globals['_HELLOREPLY']._serialized_end=232
  _globals['_XY']._serialized_start=234
  _globals['_XY']._serialized_end=260
  _globals['_XYZ']._serialized_start=262
  _globals['_XYZ']._serialized_end=300
  _globals['_XYXY']._serialized_start=302
  _globals['_XYXY']._serialized_end=364
  _globals['_XYZNEW']._serialized_start=366
  _globals['_XYZNEW']._serialized_end=416
  _globals['_XYZMAP']._serialized_start=418
  _globals['_XYZMAP']._serialized_end=468
  _globals['_GREETER']._serialized_start=471
  _globals['_GREETER']._serialized_end=715
# @@protoc_insertion_point(module_scope)
