# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main_server2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12main_server2.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n\x0bintrin_list\x12\x0e\n\x06\x63oeffs\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03ppx\x18\x04 \x01(\x02\x12\x0b\n\x03ppy\x18\x05 \x01(\x02\x12\n\n\x02\x66x\x18\x06 \x01(\x02\x12\n\n\x02\x66y\x18\x07 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x08 \x01(\x0c\"\x17\n\x03img\x12\x10\n\x08img_data\x18\x01 \x01(\x0c\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\x1a\n\x02xy\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\"&\n\x03xyz\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\x12\t\n\x01z\x18\x03 \x01(\t\">\n\x04xyxy\x12\x0c\n\x04x_lo\x18\x01 \x01(\t\x12\x0c\n\x04y_lo\x18\x02 \x01(\t\x12\x0c\n\x04x_hi\x18\x03 \x01(\t\x12\x0c\n\x04y_hi\x18\x04 \x01(\t\"2\n\x06xyznew\x12\x0c\n\x04xnew\x18\x01 \x01(\t\x12\x0c\n\x04ynew\x18\x02 \x01(\t\x12\x0c\n\x04znew\x18\x03 \x01(\t\"2\n\x06xyzmap\x12\x0c\n\x04xnew\x18\x01 \x01(\t\x12\x0c\n\x04ynew\x18\x02 \x01(\t\x12\x0c\n\x04znew\x18\x03 \x01(\t\"$\n\x0cMISBMetadata\x12\x14\n\x0cmetadataitem\x18\x01 \x01(\x0c\x32\xa4\x02\n\x07Greeter\x12*\n\nget_rframe\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x32\n\x12get_infrared_frame\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x16\n\x07\x61sk_xyz\x12\x03.xy\x1a\x04.xyz\"\x00\x12 \n\nask_xyzmap\x12\x07.xyznew\x1a\x07.xyzmap\"\x00\x12+\n\nget_intrin\x12\r.HelloRequest\x1a\x0c.intrin_list\"\x00\x12\"\n\tget_depth\x12\r.HelloRequest\x1a\x04.img\"\x00\x12.\n\x0cget_metadata\x12\r.HelloRequest\x1a\r.MISBMetadata\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_server2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTRIN_LIST']._serialized_start=55
  _globals['_INTRIN_LIST']._serialized_end=180
  _globals['_IMG']._serialized_start=182
  _globals['_IMG']._serialized_end=205
  _globals['_HELLOREQUEST']._serialized_start=207
  _globals['_HELLOREQUEST']._serialized_end=235
  _globals['_HELLOREPLY']._serialized_start=237
  _globals['_HELLOREPLY']._serialized_end=266
  _globals['_XY']._serialized_start=268
  _globals['_XY']._serialized_end=294
  _globals['_XYZ']._serialized_start=296
  _globals['_XYZ']._serialized_end=334
  _globals['_XYXY']._serialized_start=336
  _globals['_XYXY']._serialized_end=398
  _globals['_XYZNEW']._serialized_start=400
  _globals['_XYZNEW']._serialized_end=450
  _globals['_XYZMAP']._serialized_start=452
  _globals['_XYZMAP']._serialized_end=502
  _globals['_MISBMETADATA']._serialized_start=504
  _globals['_MISBMETADATA']._serialized_end=540
  _globals['_GREETER']._serialized_start=543
  _globals['_GREETER']._serialized_end=835
# @@protoc_insertion_point(module_scope)
