# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import newMOT_pb2 as newMOT__pb2


class MOTorStub(object):
    """same as class in server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.askInfer_MOT = channel.unary_unary(
                '/MOTor/askInfer_MOT',
                request_serializer=newMOT__pb2.MOT_pic.SerializeToString,
                response_deserializer=newMOT__pb2.MOT_reply.FromString,
                )


class MOTorServicer(object):
    """same as class in server
    """

    def askInfer_MOT(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MOTorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'askInfer_MOT': grpc.unary_unary_rpc_method_handler(
                    servicer.askInfer_MOT,
                    request_deserializer=newMOT__pb2.MOT_pic.FromString,
                    response_serializer=newMOT__pb2.MOT_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MOTor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MOTor(object):
    """same as class in server
    """

    @staticmethod
    def askInfer_MOT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MOTor/askInfer_MOT',
            newMOT__pb2.MOT_pic.SerializeToString,
            newMOT__pb2.MOT_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
