# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newMOT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnewMOT.proto\"\x18\n\x07MOT_pic\x12\r\n\x05image\x18\x01 \x01(\t\"C\n\tMOT_reply\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\'\n\ndetections\x18\x02 \x03(\x0b\x32\x13.SingleMOTDetection\"\x81\x01\n\x12SingleMOTDetection\x12\r\n\x05x_low\x18\x01 \x01(\x02\x12\r\n\x05y_low\x18\x02 \x01(\x02\x12\x0e\n\x06x_high\x18\x03 \x01(\x02\x12\x0e\n\x06y_high\x18\x04 \x01(\x02\x12\n\n\x02id\x18\x05 \x01(\x05\x12\r\n\x05\x63lass\x18\x06 \x01(\x05\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x32/\n\x05MOTor\x12&\n\x0c\x61skInfer_MOT\x12\x08.MOT_pic\x1a\n.MOT_reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'newMOT_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOT_PIC']._serialized_start=16
  _globals['_MOT_PIC']._serialized_end=40
  _globals['_MOT_REPLY']._serialized_start=42
  _globals['_MOT_REPLY']._serialized_end=109
  _globals['_SINGLEMOTDETECTION']._serialized_start=112
  _globals['_SINGLEMOTDETECTION']._serialized_end=241
  _globals['_MOTOR']._serialized_start=243
  _globals['_MOTOR']._serialized_end=290
# @@protoc_insertion_point(module_scope)
