# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objDetect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fobjDetect.proto\"\x1d\n\robjDetect_pic\x12\x0c\n\x04name\x18\x01 \x01(\t\"Z\n\x0fobjDetect_reply\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x12\x0c\n\x04x_lo\x18\x02 \x01(\t\x12\x0c\n\x04y_lo\x18\x03 \x01(\t\x12\x0c\n\x04x_hi\x18\x04 \x01(\t\x12\x0c\n\x04y_hi\x18\x05 \x01(\t2G\n\x0bobjDetector\x12\x38\n\x12\x61skInfer_objDetect\x12\x0e.objDetect_pic\x1a\x10.objDetect_reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objDetect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJDETECT_PIC._serialized_start=19
  _OBJDETECT_PIC._serialized_end=48
  _OBJDETECT_REPLY._serialized_start=50
  _OBJDETECT_REPLY._serialized_end=140
  _OBJDETECTOR._serialized_start=142
  _OBJDETECTOR._serialized_end=213
# @@protoc_insertion_point(module_scope)
