# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import objDetect_pb2 as objDetect__pb2


class objDetectorStub(object):
    """same as class in server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.askInfer_objDetect = channel.unary_unary(
                '/objDetector/askInfer_objDetect',
                request_serializer=objDetect__pb2.objDetect_pic.SerializeToString,
                response_deserializer=objDetect__pb2.objDetect_reply.FromString,
                )


class objDetectorServicer(object):
    """same as class in server
    """

    def askInfer_objDetect(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_objDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'askInfer_objDetect': grpc.unary_unary_rpc_method_handler(
                    servicer.askInfer_objDetect,
                    request_deserializer=objDetect__pb2.objDetect_pic.FromString,
                    response_serializer=objDetect__pb2.objDetect_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class objDetector(object):
    """same as class in server
    """

    @staticmethod
    def askInfer_objDetect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/objDetector/askInfer_objDetect',
            objDetect__pb2.objDetect_pic.SerializeToString,
            objDetect__pb2.objDetect_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
