# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import object_detection_pb2 as object__detection__pb2


class objDetectorStub(object):
    """same as class in server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer_object_detection = channel.unary_unary(
                '/objDetector/infer_object_detection',
                request_serializer=object__detection__pb2.ObjectDetectionImage.SerializeToString,
                response_deserializer=object__detection__pb2.ObjectDetectionReply.FromString,
                )


class objDetectorServicer(object):
    """same as class in server
    """

    def infer_object_detection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_objDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer_object_detection': grpc.unary_unary_rpc_method_handler(
                    servicer.infer_object_detection,
                    request_deserializer=object__detection__pb2.ObjectDetectionImage.FromString,
                    response_serializer=object__detection__pb2.ObjectDetectionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class objDetector(object):
    """same as class in server
    """

    @staticmethod
    def infer_object_detection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/objDetector/infer_object_detection',
            object__detection__pb2.ObjectDetectionImage.SerializeToString,
            object__detection__pb2.ObjectDetectionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
