# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16object_detection.proto\"%\n\x14ObjectDetectionImage\x12\r\n\x05image\x18\x01 \x01(\t\"Q\n\x14ObjectDetectionReply\x12\r\n\x05image\x18\x01 \x01(\x0c\x12*\n\ndetections\x18\x02 \x03(\x0b\x32\x16.SingleObjectDetection\"}\n\x15SingleObjectDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\r\n\x05x_low\x18\x02 \x01(\x02\x12\r\n\x05y_low\x18\x03 \x01(\x02\x12\x0e\n\x06x_high\x18\x04 \x01(\x02\x12\x0e\n\x06y_high\x18\x05 \x01(\x02\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x32W\n\x0bobjDetector\x12H\n\x16infer_object_detection\x12\x15.ObjectDetectionImage\x1a\x15.ObjectDetectionReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECTDETECTIONIMAGE']._serialized_start=26
  _globals['_OBJECTDETECTIONIMAGE']._serialized_end=63
  _globals['_OBJECTDETECTIONREPLY']._serialized_start=65
  _globals['_OBJECTDETECTIONREPLY']._serialized_end=146
  _globals['_SINGLEOBJECTDETECTION']._serialized_start=148
  _globals['_SINGLEOBJECTDETECTION']._serialized_end=273
  _globals['_OBJDETECTOR']._serialized_start=275
  _globals['_OBJDETECTOR']._serialized_end=362
# @@protoc_insertion_point(module_scope)
