# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poseEst.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rposeEst.proto\"\x1b\n\x0bposeEst_pic\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rposeEst_reply\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32?\n\tposeEstor\x12\x32\n\x10\x61skInfer_poseEst\x12\x0c.poseEst_pic\x1a\x0e.poseEst_reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poseEst_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSEEST_PIC._serialized_start=17
  _POSEEST_PIC._serialized_end=44
  _POSEEST_REPLY._serialized_start=46
  _POSEEST_REPLY._serialized_end=78
  _POSEESTOR._serialized_start=80
  _POSEESTOR._serialized_end=143
# @@protoc_insertion_point(module_scope)
