# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import poseEst_pb2 as poseEst__pb2


class poseEstorStub(object):
    """same as class in server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.askInfer_poseEst = channel.unary_unary(
                '/poseEstor/askInfer_poseEst',
                request_serializer=poseEst__pb2.poseEst_pic.SerializeToString,
                response_deserializer=poseEst__pb2.poseEst_reply.FromString,
                )


class poseEstorServicer(object):
    """same as class in server
    """

    def askInfer_poseEst(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_poseEstorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'askInfer_poseEst': grpc.unary_unary_rpc_method_handler(
                    servicer.askInfer_poseEst,
                    request_deserializer=poseEst__pb2.poseEst_pic.FromString,
                    response_serializer=poseEst__pb2.poseEst_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poseEstor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class poseEstor(object):
    """same as class in server
    """

    @staticmethod
    def askInfer_poseEst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poseEstor/askInfer_poseEst',
            poseEst__pb2.poseEst_pic.SerializeToString,
            poseEst__pb2.poseEst_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
